[package]
name = "zippy-rs"
version = "0.1.0"
authors = ["Adrian Kumpf <adrian.kumpf@posteo.de>"]
edition = '2018'

[dependencies]
reqwest = "0.9.5"
meval = "0.2.0"
rayon = "1.0.3"
structopt = { version = "0.2", default-features = false }
